### ISSUE TITLE
리뷰입니다

### ISSUE THREAD

**Issue by Gimwooeung** [BangTtagGum/MyBlog-Server#13]
##1. Controller패키지 안에 message패키지가 있는데 굳이 따로 패키지로 안 만드시고
dto쪽에서 출력이 되도록 했으면 좋을 것 같아요.

##2. 사용하지 않은 security 패키지는 제외하면 좋을 것 같아요
jwt에서 JwtUtil파일만 사용해서 코드를 구현할 수 있어요.

![이슈](https://github.com/BangTtagGum/MyBlog-Server/assets/132888708/0c87810c-979b-4b26-ace4-a4458b517164)

**Comment by BangTtagGum** [comment]
리뷰 감사합니다
