### ISSUE TITLE
리뷰 입니다.

### ISSUE THREAD

**Issue by Gimwooeung** [BangTtagGum/MyBlog-Server#19]
제가 많이 부족하여 많은 것이 보이지 않지만 같은 과정을 배웠음에도 불구하고 서로 비슷한 듯 다른 구현이 되는 것을 보고 많이 배워갑니다. 다음 과제에서 많이 참고하겠습니다 ㅎㅎㅎ

**Comment by BangTtagGum** [comment]
좋은 리뷰 감사합니다
